### ISSUE TITLE
[TODO]: Bump version to 0.10.0

### ISSUE THREAD

**Issue by Jacrispys** [InsideAgent/InsideAgentBot#17]
### Feature Request requirements.

- [X] I have searched the [issues](https://github.com/InsideAgent/InsideAgentBot/issues) page for duplicates.
- [X] I have checked the [Pull Request](https://github.com/InsideAgent/InsideAgentBot/pulls) page for this feature.
- [X] I am willing to PR this feature myself.
- [ ] I have external information to clarify the request (photo/video/files/links).

### Description

Commit a version bump to main & create a release

### Please attach any other files/screenshots/videos/information below!

Go through all parts of the project and update where applicable version, as well as writing release notes & project plans for the future.

**Comment by Jacrispys** [comment]
https://github.com/InsideAgent/InsideAgentBot/releases/tag/v0.10.0
